version: '3'
services:
  network:
    build: ./network/
    ports:
      - "5000:5000"
  app:
    build: ./app_data/
    ports:
      - "5001:5001"
    depends_on:
      - network
  cron:
    build: ./cron_refresh/
    depends_on:
      - app
