version: '3'
services:
  network:
    build: ./network_server/
    ports:
      - "5000:5000"
  app:
    build: ./app_server/
    ports:
      - "5001:5001"
    depends_on:
      - network
  cron:
    build: ./cron/
    depends_on:
      - app
