
FROM ubuntu
RUN apt-get update
RUN apt-get -y install nodejs
RUN apt-get -y install npm

RUN mkdir React_dashboard
COPY ./React_dashboard ./React_dashboard

RUN cd ./React_dashboard
RUN npm i

EXPOSE 3000

CMD ["npm", "start"]
